language: go

go:
  - 1.18
env:
  - GO111MODULE=on # 启用Go mod
script:
  - sh build.sh
before_deploy: make build-all # 发布前执行生成二进制文件的命令
deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    repo: YouCD/PrometheusAlertFire
    # tag才触发发布
    tags: true